/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import entities.Evenement;
import entities.Inscription;
import entities.Participant;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import service.EvenementService;
import service.InscriptionService;
import service.ParticipantService;

/**
 *
 * @author X1 YOGA
 */
public class InscriptionPanel extends javax.swing.JInternalFrame {

    /**
     * Creates new form InscriptionPanel
     */
    private InscriptionService inscriptionService;
    private EvenementService evenementService;
    private ParticipantService participantService;
    private DefaultTableModel model;
    public InscriptionPanel() {
        initComponents();
        inscriptionService = new InscriptionService();
        evenementService = new EvenementService();
        participantService = new ParticipantService();
        model = (DefaultTableModel) inscription.getModel();

// Charger les données initiales
      loadEvenements();
      loadParticipants();
      loadInscriptions();
      updateTauxRemplissage();
       
    }
  private void loadEvenements() {
    evenements.removeAllItems();
    for (Evenement e : evenementService.findAll()) {
        evenements.addItem(e);  // Objet directement
    }
}

private void loadParticipants() {
    participants.removeAllItems();
    for (Participant p : participantService.findAll()) {
        participants.addItem(p);  // Objet directement
    }
}

private void loadInscriptions() {
    model.setRowCount(0);
    for (Inscription i : inscriptionService.findAll()) {
        model.addRow(new Object[]{
            i.getId(),
            i.getEvenement().getTitre(),
            i.getParticipant().getNom(),
            i.getParticipant().getEmail(),
            i.getDateInscription()
        });
    }
}

private void clearFields() {
    evenements.setSelectedIndex(0);
    participants.setSelectedIndex(0);
    dateIN.setDate(new Date());
    updateTauxRemplissage();
}
private void updateTauxRemplissage() {
    if (evenements.getSelectedItem() != null) {
        Evenement evenementSelectionne = (Evenement) evenements.getSelectedItem(); 
        
        int taux = inscriptionService.tauxRemplissage(evenementSelectionne.getId_evenement());
        tauxLabel.setText("Taux de remplissage: " + taux + "%");
        
        if (taux < 50) {
            tauxLabel.setForeground(new java.awt.Color(0, 153, 0));
        } else if (taux < 80) {
            tauxLabel.setForeground(new java.awt.Color(255, 153, 0));
        } else if (taux < 100) {
            tauxLabel.setForeground(new java.awt.Color(204, 0, 0));
        } else {
            tauxLabel.setForeground(new java.awt.Color(153, 0, 0));
            tauxLabel.setText("Taux de remplissage: " + taux + "% - COMPLET!");
        }
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        evenements = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        participants = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        dateIN = new com.toedter.calendar.JDateChooser();
        inscrire = new javax.swing.JButton();
        modifier = new javax.swing.JButton();
        supprimer = new javax.swing.JButton();
        tauxLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        inscription = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestion des Inscriptions");
        setPreferredSize(new java.awt.Dimension(1650, 1350));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Formulaire d'lnscription", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16), new java.awt.Color(153, 0, 255))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(153, 0, 255));
        jPanel1.setToolTipText("");
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 500));

        jLabel1.setBackground(new java.awt.Color(153, 0, 255));
        jLabel1.setForeground(new java.awt.Color(153, 51, 255));
        jLabel1.setText("Sélectionner un événement:");

        evenements.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evenementsActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(153, 0, 255));
        jLabel2.setForeground(new java.awt.Color(153, 0, 255));
        jLabel2.setText("Sélectionner un participant:");

        participants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                participantsActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(153, 0, 204));
        jLabel3.setText("Date d'inscription:");

        inscrire.setBackground(new java.awt.Color(0, 204, 102));
        inscrire.setText("Inscrire");
        inscrire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscrireActionPerformed(evt);
            }
        });

        modifier.setBackground(new java.awt.Color(255, 153, 0));
        modifier.setText("Modifier");
        modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierActionPerformed(evt);
            }
        });

        supprimer.setBackground(new java.awt.Color(204, 0, 51));
        supprimer.setText("Supprimer");
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });

        tauxLabel.setBackground(new java.awt.Color(153, 0, 204));
        tauxLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tauxLabel.setForeground(new java.awt.Color(153, 0, 255));
        tauxLabel.setText("Taux de remplissage: %");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(evenements, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(participants, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 70, Short.MAX_VALUE))
                            .addComponent(dateIN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(inscrire, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tauxLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(184, 184, 184))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(evenements, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(tauxLabel)
                .addGap(52, 52, 52)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addComponent(participants, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addGap(32, 32, 32)
                .addComponent(dateIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supprimer)
                    .addComponent(modifier)
                    .addComponent(inscrire))
                .addContainerGap(291, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Liste des Inscriptions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16), new java.awt.Color(153, 0, 255))); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(700, 500));

        inscription.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Evenements", "Participant", "Email", "DateInscription"
            }
        ));
        inscription.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inscriptionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(inscription);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void evenementsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evenementsActionPerformed
        updateTauxRemplissage(); 
    }//GEN-LAST:event_evenementsActionPerformed

    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierActionPerformed
         int selectedRow = inscription.getSelectedRow();
        
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, 
                "Veuillez sélectionner une inscription à modifier!", 
                "Avertissement", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Vérifier que tous les champs sont remplis
        if (evenements.getSelectedItem() == null || participants.getSelectedItem() == null || dateIN.getDate() == null) {
            JOptionPane.showMessageDialog(this, 
                "Veuillez remplir tous les champs!", 
                "Erreur", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        int id = Integer.parseInt(model.getValueAt(selectedRow, 0).toString());
        
        // Récupérer l'événement
        String evenementNom = evenements.getSelectedItem().toString();
        Evenement evenement = null;
        for (Evenement e : evenementService.findAll()) {
            if (e.getTitre().equals(evenementNom)) {
                evenement = e;
                break;
            }
        }

        // Récupérer le participant
        String participantInfo = participants.getSelectedItem().toString();
        String participantNom = participantInfo.split(" - ")[0];
        Participant participant = null;
        for (Participant p : participantService.findAll()) {
            if (p.getNom().equals(participantNom)) {
                participant = p;
                break;
            }
        }

        Date dateInscription = dateIN.getDate();

        Inscription inscriptionModifiee = new Inscription(id, evenement, participant, dateInscription);
        
        if (inscriptionService.update(inscriptionModifiee)) {
            JOptionPane.showMessageDialog(this, 
                "Inscription modifiée avec succès!", 
                "Succès", 
                JOptionPane.INFORMATION_MESSAGE);
            loadInscriptions();
            updateTauxRemplissage(); // IMPORTANT: Mettre à jour le taux
            clearFields();
        } else {
            JOptionPane.showMessageDialog(this, 
                "Erreur lors de la modification!", 
                "Erreur", 
                JOptionPane.ERROR_MESSAGE);
        }
    
        
    }//GEN-LAST:event_modifierActionPerformed

    private void inscrireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscrireActionPerformed
             try {
        Date dateInscription = dateIN.getDate();
        Participant participant = (Participant) participants.getSelectedItem();
        Evenement evenement = (Evenement) evenements.getSelectedItem();

        if (dateInscription == null || participant == null || evenement == null) {
            JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs!", "Erreur", JOptionPane.ERROR_MESSAGE);
            return;
        }

        boolean success = inscriptionService.create(new Inscription(evenement, participant, dateInscription));

        if (success) {
            JOptionPane.showMessageDialog(this, "Inscription ajoutée avec succès!", "Succès", JOptionPane.INFORMATION_MESSAGE);
            loadInscriptions();
            updateTauxRemplissage();
            clearFields();
        } else {
            JOptionPane.showMessageDialog(this, "Erreur lors de l'ajout de l'inscription!", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    } catch (NumberFormatException nfe) {
        JOptionPane.showMessageDialog(this, "Erreur de format des données!", "Erreur", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erreur inattendue: " + e.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_inscrireActionPerformed

    private void inscriptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inscriptionMouseClicked

    int selectedRow = inscription.getSelectedRow();
    if (selectedRow != -1) {
        String evenementNom = model.getValueAt(selectedRow, 1).toString();
        String participantNom = model.getValueAt(selectedRow, 2).toString();
        Date dateInsc = (Date) model.getValueAt(selectedRow, 4);
        
        // Chercher l'événement dans le combo
        for (int i = 0; i < evenements.getItemCount(); i++) {
            Evenement e = (Evenement) evenements.getItemAt(i);
            if (e.getTitre().equals(evenementNom)) {
                evenements.setSelectedIndex(i);
                break;
            }
        }
        
        // Chercher le participant dans le combo
        for (int i = 0; i < participants.getItemCount(); i++) {
            Participant p = (Participant) participants.getItemAt(i);
            if (p.getNom().equals(participantNom)) {
                participants.setSelectedIndex(i);
                break;
            }
        }
        
        dateIN.setDate(dateInsc);
    }

            
    }//GEN-LAST:event_inscriptionMouseClicked

    private void participantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_participantsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_participantsActionPerformed

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
      try {
        int selectedRow = inscription.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner une inscription à supprimer!", "Avertissement", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirmation = JOptionPane.showConfirmDialog(this, "Êtes-vous sûr de vouloir supprimer cette inscription?", "Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

        if (confirmation == JOptionPane.YES_OPTION) {
            int id = Integer.parseInt(model.getValueAt(selectedRow, 0).toString());
            Inscription inscriptionASupprimer = inscriptionService.findById(id);

            if (inscriptionASupprimer != null && inscriptionService.delete(inscriptionASupprimer)) {
                JOptionPane.showMessageDialog(this, "Inscription supprimée avec succès!", "Succès", JOptionPane.INFORMATION_MESSAGE);
                loadInscriptions();
                updateTauxRemplissage();
                clearFields();
            } else {
                JOptionPane.showMessageDialog(this, "Erreur lors de la suppression!", "Erreur", JOptionPane.ERROR_MESSAGE);
            }
        }
    } catch (NumberFormatException nfe) {
        JOptionPane.showMessageDialog(this, "Erreur de format des données!", "Erreur", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erreur inattendue: " + e.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_supprimerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dateIN;
    private javax.swing.JComboBox evenements;
    private javax.swing.JTable inscription;
    private javax.swing.JButton inscrire;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modifier;
    private javax.swing.JComboBox participants;
    private javax.swing.JButton supprimer;
    private javax.swing.JLabel tauxLabel;
    // End of variables declaration//GEN-END:variables
}
