/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import connexion.Connexion;
import java.awt.BorderLayout; 
import java.awt.PopupMenu;
import javax.swing.BoxLayout;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author X1 YOGA
 */
public class Mainfram extends javax.swing.JFrame {

    /**
     * Creates new form Mainfram
     */
    public Mainfram() {
        initComponents();
        
        
      

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        evenement = new javax.swing.JMenuItem();
        participant = new javax.swing.JMenuItem();
        insription = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        graphe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1650, 1350));

        fileMenu.setBackground(new java.awt.Color(255, 255, 255));
        fileMenu.setForeground(new java.awt.Color(153, 0, 255));
        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        evenement.setMnemonic('o');
        evenement.setText("Gestion des evenements");
        evenement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evenementActionPerformed(evt);
            }
        });
        fileMenu.add(evenement);

        participant.setMnemonic('s');
        participant.setText("Gestion des participant");
        participant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                participantActionPerformed(evt);
            }
        });
        fileMenu.add(participant);

        insription.setMnemonic('a');
        insription.setText("Gestion des inscription");
        insription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insriptionActionPerformed(evt);
            }
        });
        fileMenu.add(insription);

        menuBar.add(fileMenu);

        editMenu.setBackground(new java.awt.Color(255, 255, 255));
        editMenu.setForeground(new java.awt.Color(153, 0, 255));
        editMenu.setMnemonic('e');
        editMenu.setText("Filtrer");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Voir Le Filtrage");
        cutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(cutMenuItem);

        menuBar.add(editMenu);

        helpMenu.setBackground(new java.awt.Color(255, 255, 255));
        helpMenu.setForeground(new java.awt.Color(153, 0, 255));
        helpMenu.setMnemonic('h');
        helpMenu.setText("Graphe");

        graphe.setMnemonic('c');
        graphe.setText("voir les graphe");
        graphe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grapheActionPerformed(evt);
            }
        });
        helpMenu.add(graphe);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1608, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1350, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insriptionActionPerformed
         InscriptionPanel ins=new InscriptionPanel();
                  desktopPane.add(ins );
                  ins.setVisible(true);
    }//GEN-LAST:event_insriptionActionPerformed

    private void evenementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evenementActionPerformed
         EvenementPanel pp=new  EvenementPanel ();
                desktopPane.add(pp);
                pp.setVisible(true);
    }//GEN-LAST:event_evenementActionPerformed

    private void participantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_participantActionPerformed
        ParticipantPanel ps=new ParticipantPanel ();
                  desktopPane.add(ps );
                  ps.setVisible(true);
    }//GEN-LAST:event_participantActionPerformed

    private void cutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuItemActionPerformed
       StatistiquesPanel stats = new StatistiquesPanel();
    desktopPane.add(stats);
    stats.setVisible(true);
    try {
        stats.setMaximum(true);
    } catch (java.beans.PropertyVetoException e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_cutMenuItemActionPerformed

    private void grapheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grapheActionPerformed
          GraphPanel gp = new GraphPanel();
    desktopPane.add(gp);
    gp.setVisible(true);

    try {
        gp.setMaximum(true); // Afficher en plein écran dans le desktopPane
    } catch (java.beans.PropertyVetoException e) {
        e.printStackTrace();
    }
    }                                     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
         
        JFrame frame = new JFrame("Connexion");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        // Dans votre logginPanel, quand vous ouvrez Mainfram :
  
        
        JDesktopPane desktop = new JDesktopPane();
        frame.setContentPane(desktop);
        frame.setSize(1700, 1500);
        frame.setLocationRelativeTo(null); 

       logginPanel loginInternal = new logginPanel();
       desktop.add(loginInternal);
       loginInternal.setSize(800, 1500); // taille du formulaire
        loginInternal.setVisible(true);

        frame.setVisible(true);
    }});
    }//GEN-LAST:event_grapheActionPerformed

    /**
     * @param args the command line arguments
     */
                

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem evenement;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem graphe;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem insription;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem participant;
    // End of variables declaration//GEN-END:variables

}
