/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import entities.Evenement;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import service.EvenementService;
import service.InscriptionService;

/**
 *
 * @author X1 YOGA
 */
public class StatistiquesPanel extends javax.swing.JInternalFrame {

    /**
     * Creates new form StatistiquesPanel
     */
    private EvenementService evenementService;
    private InscriptionService inscriptionService;
    private DefaultTableModel model;
    private List<Evenement> evenementsFiltres;
    public StatistiquesPanel() {
        initComponents();
        evenementService = new EvenementService();
        inscriptionService = new InscriptionService();
        model = (DefaultTableModel) tableauEvenements.getModel();
         evenementsFiltres = new ArrayList<>();
    
    // Configurer le modèle du tableau
    model.setColumnIdentifiers(new String[]{"ID", "Titre", "Lieu", "Date", "Capacité", "Inscriptions", "Taux"});
    
    loadAllData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void loadAllData() {
    evenementsFiltres = evenementService.findAll();
    updateTable();
}
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        filtreTexte = new javax.swing.JTextField();
        btnFiltrerLieu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableauEvenements = new javax.swing.JTable();

        setBackground(new java.awt.Color(102, 0, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Statistiques et Graphiques");
        setPreferredSize(new java.awt.Dimension(700, 500));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filtres", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16), new java.awt.Color(153, 0, 255))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(153, 51, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 255));
        jLabel1.setText("Filtrer par Lieu :");

        btnFiltrerLieu.setBackground(new java.awt.Color(0, 153, 204));
        btnFiltrerLieu.setForeground(new java.awt.Color(255, 255, 255));
        btnFiltrerLieu.setText("Filtrer");
        btnFiltrerLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrerLieuActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 204));
        jLabel2.setText("Filtrer par Date:");

        jButton1.setBackground(new java.awt.Color(51, 0, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Filtrer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(102, 0, 102));
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("Réinitialiser");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(filtreTexte)
            .addComponent(btnFiltrerLieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filtreTexte, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFiltrerLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tableauEvenements.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "titre", "dateEv", "capacite"
            }
        ));
        jScrollPane1.setViewportView(tableauEvenements);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnFiltrerLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrerLieuActionPerformed
                                              
    String lieu = filtreTexte.getText().trim();
    
    if (lieu.isEmpty()) {
        JOptionPane.showMessageDialog(this, 
            "Veuillez entrer un lieu!", 
            "Attention", 
            JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    evenementsFiltres = evenementService.findByLieu(lieu);
    
    if (evenementsFiltres.isEmpty()) {
        JOptionPane.showMessageDialog(this, 
            "Aucun événement trouvé pour ce lieu: " + lieu, 
            "Information", 
            JOptionPane.INFORMATION_MESSAGE);
        evenementsFiltres = new ArrayList<>();
    } else {
        JOptionPane.showMessageDialog(this, 
            evenementsFiltres.size() + " événement(s) trouvé(s) pour le lieu: " + lieu, 
            "Résultat", 
            JOptionPane.INFORMATION_MESSAGE);
    }
    
    updateTable();

    }//GEN-LAST:event_btnFiltrerLieuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Date date = jDateChooser1.getDate();
    
    if (date == null) {
        JOptionPane.showMessageDialog(this, 
            "Veuillez sélectionner une date!", 
            "Attention", 
            JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    evenementsFiltres = evenementService.findByDate(date);
    
    if (evenementsFiltres.isEmpty()) {
        JOptionPane.showMessageDialog(this, 
            "Aucun événement trouvé pour cette date!", 
            "Information", 
            JOptionPane.INFORMATION_MESSAGE);
        evenementsFiltres = new ArrayList<>();
    } else {
        JOptionPane.showMessageDialog(this, 
            evenementsFiltres.size() + " événement(s) trouvé(s) pour cette date!", 
            "Résultat", 
            JOptionPane.INFORMATION_MESSAGE);
    }
    
    updateTable();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltrerLieu;
    private javax.swing.JButton btnReset;
    private javax.swing.JTextField filtreTexte;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableauEvenements;
    // End of variables declaration//GEN-END:variables

    private void updateTable() {
       model.setRowCount(0);
    for (Evenement e : evenementsFiltres) {
        int nbInscriptions = inscriptionService.countByEvenement(e.getId_evenement());
        int taux = inscriptionService.tauxRemplissage(e.getId_evenement());
        
        model.addRow(new Object[]{
            e.getId_evenement(),
            e.getTitre(),
            e.getLieu(),
            e.getDateEv(),
            e.getCapacite(),
            nbInscriptions,
            taux + "%"
        });
    }}
}
